Repository googlemaps/openapi-specification, pull requests merged in 2021-09, with the labels that each got.

#192 fix: split docs for geocoding vs reverse geocoding
  dist/documentation/parameters/maps_http_parameters_geocode.html
  dist/documentation/parameters/maps_http_parameters_geocode.md
  dist/documentation/parameters/maps_http_parameters_geocode_reverse.html
  dist/documentation/parameters/maps_http_parameters_geocode_reverse.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  generator/documentation/parameters.ts
  specification/parameters/geocode/address.yml
  specification/parameters/geocode/bounds.yml
  specification/parameters/geocode/components.yml
  specification/parameters/geocode/location_type.yml
  specification/parameters/geocode/result_type.yml
  specification/paths/geocode.yml
Labels: cla: yes

#196 fix: typo in place description
  dist/documentation/schemas/maps_http_schema_place.html
  dist/documentation/schemas/maps_http_schema_place.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/Place.yml
Labels: cla: yes, merge

#198 fix: add en to region param
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/region.yml
Labels: cla: yes, merge

#200 fix: add operation id
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/paths/_index.yml
Labels: cla: yes, merge

#201 fix: typo in place review
  dist/documentation/schemas/maps_http_schema_placereview.html
  dist/documentation/schemas/maps_http_schema_placereview.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/PlaceReview.yml
Labels: cla: yes

#203 fix: use backticks
  dist/documentation/parameters/maps_http_parameters_elevation.html
  dist/documentation/parameters/maps_http_parameters_elevation.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/elevation/path.yml
Labels: cla: yes

#206 Fix: add examples of multi-type failures
  dist/documentation/parameters/maps_http_parameters_placenearbysearch.html
  dist/documentation/parameters/maps_http_parameters_placenearbysearch.md
  dist/documentation/parameters/maps_http_parameters_placetextsearch.html
  dist/documentation/parameters/maps_http_parameters_placetextsearch.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/places/type.yml
Labels: cla: no

#210 fix: separate units parameter
  dist/documentation/parameters/maps_http_parameters_distancematrix.html
  dist/documentation/parameters/maps_http_parameters_distancematrix.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/directions/units.yml
  specification/parameters/distanceMatrix/units.yml
  specification/paths/directions.yml
  specification/paths/distanceMatrix.yml
Labels: cla: yes

#211 fix: update DistanceMatrixResponse to add caution about parsing b/130399550
  dist/documentation/schemas/maps_http_schema_distancematrixresponse.html
  dist/documentation/schemas/maps_http_schema_distancematrixresponse.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/DistanceMatrixResponse.yml
Labels: cla: no

#212 fix: directions response
  dist/documentation/schemas/maps_http_schema_directionsresponse.html
  dist/documentation/schemas/maps_http_schema_directionsresponse.md
  dist/documentation/schemas/maps_http_schema_elevationresponse.html
  dist/documentation/schemas/maps_http_schema_elevationresponse.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.go
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.java
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.js
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.py
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.rb
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.sh
  dist/snippets/maps_http_directions_invalid/maps_http_directions_invalid.txt
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.go
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.java
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.js
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.py
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.rb
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.sh
  dist/snippets/maps_http_directions_zero_results/maps_http_directions_zero_results.txt
  generator/requests/requests.ts
  specification/paths/directions.yml
  specification/responses/maps_http_directions_invalid_response.xml
  specification/responses/maps_http_directions_invalid_response.yml
  specification/responses/maps_http_directions_zero_results_response.xml
  specification/responses/maps_http_directions_zero_results_response.yml
  specification/schemas/DirectionsResponse.yml
  specification/schemas/ElevationResponse.yml
Labels: cla: yes

#213 Update PlaceAutocompletePrediction.yml - fix for
  dist/documentation/schemas/maps_http_schema_placeautocompleteprediction.html
  dist/documentation/schemas/maps_http_schema_placeautocompleteprediction.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/PlaceAutocompletePrediction.yml
Labels: cla: no

#214 Update Place.yml - fix for 130399550
  dist/documentation/schemas/maps_http_schema_place.html
  dist/documentation/schemas/maps_http_schema_place.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/Place.yml
Labels: cla: no

#218 fix: language is optional
  dist/documentation/schemas/maps_http_schema_placereview.html
  dist/documentation/schemas/maps_http_schema_placereview.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/PlaceReview.yml
Labels: cla: yes, merge

#220 fix: improve description of vicinity
  dist/documentation/schemas/maps_http_schema_place.html
  dist/documentation/schemas/maps_http_schema_place.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/Place.yml
Labels: cla: yes

#223 fix: query autocomplete snippets path
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.go
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.java
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.js
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.py
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.rb
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.sh
  dist/snippets/maps_http_places_queryautocomplete_location_weighted/maps_http_places_queryautocomplete_location_weighted.txt
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.go
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.java
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.js
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.py
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.rb
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.sh
  dist/snippets/maps_http_places_queryautocomplete_pizza/maps_http_places_queryautocomplete_pizza.txt
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.go
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.java
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.js
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.py
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.rb
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.sh
  dist/snippets/maps_http_places_queryautocomplete_pizza_fr/maps_http_places_queryautocomplete_pizza_fr.txt
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.go
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.java
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.js
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.py
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.rb
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.sh
  dist/snippets/maps_http_places_queryautocomplete_pizza_sydney/maps_http_places_queryautocomplete_pizza_sydney.txt
  generator/requests/requests.ts
  specification/responses/maps_http_places_queryautocomplete_location_weighted_response.xml
  specification/responses/maps_http_places_queryautocomplete_location_weighted_response.yml
  specification/responses/maps_http_places_queryautocomplete_pizza_fr_response.xml
  specification/responses/maps_http_places_queryautocomplete_pizza_fr_response.yml
  specification/responses/maps_http_places_queryautocomplete_pizza_response.xml
  specification/responses/maps_http_places_queryautocomplete_pizza_response.yml
  specification/responses/maps_http_places_queryautocomplete_pizza_sydney_response.xml
  specification/responses/maps_http_places_queryautocomplete_pizza_sydney_response.yml
Labels: cla: yes

#222 fix: generate parameter index as part of build
  BUILD.bazel
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  package.json
  rules/BUILD.bazel
  rules/parameters.ts
  specification/parameters/_index.yml
Labels: cla: yes, merge

#224 chore: Synced file(s) with googlemaps/.github
  SECURITY.md
Labels: cla: yes, merge, file-sync
