Repository googlemaps/openapi-specification, pull requests merged in 2021-11, with the labels that each got.

#246 fix: description for weekday_text
  dist/documentation/schemas/maps_http_schema_placeopeninghours.html
  dist/documentation/schemas/maps_http_schema_placeopeninghours.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/PlaceOpeningHours.yml
Labels: automerge, cla: yes, merge

#249 fix: remove API from tag name
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/index.yml
Labels: cla: yes

#251 fix: lowercase mode
  dist/documentation/parameters/maps_http_parameters_directions.html
  dist/documentation/parameters/maps_http_parameters_directions.md
  dist/documentation/parameters/maps_http_parameters_distancematrix.html
  dist/documentation/parameters/maps_http_parameters_distancematrix.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/mode.yml
Labels: cla: yes, merge

#252 fix: updated and moved caution text
  dist/documentation/parameters/maps_http_parameters_placedetails.html
  dist/documentation/parameters/maps_http_parameters_placedetails.md
  dist/documentation/parameters/maps_http_parameters_placefindplacefromtext.html
  dist/documentation/parameters/maps_http_parameters_placefindplacefromtext.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/parameters/places/fields.yml
Labels: cla: yes

#257 chore: fix typo
  dist/documentation/schemas/maps_http_schema_directionsresponse.html
  dist/documentation/schemas/maps_http_schema_directionsresponse.md
  dist/google-maps-platform-openapi3.json
  dist/google-maps-platform-openapi3.yml
  dist/google-maps-platform-postman.json
  specification/schemas/DirectionsResponse.yml
Labels: cla: yes
